name: Firebase Deploy

on:
  push:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # リポジトリのコードをチェックアウト（クローン）するために使用される
      - uses: actions/checkout@v4
      - name: Set up Node.js
    # GitHubが提供する公式のNode.jsセットアップアクションです。このアクションを使うことで、ワークフロー内でNode.js環境を整えることができる
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build

  deploy:
    runs-on: ubuntu-latest
    # GitHub Actionsのワークフロー内でジョブの依存関係を指定するために使用される
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Production
      run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
      # run: |
# echo "Deploying to production server..."
# # デプロイメントスクリプトをここに記述


# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#         with:
#           node-version: '12'
#       - run: npm ci
#       - run: npm run build
#       - name: GitHub Action for Firebase
#         uses: w9jds/firebase-action@v1.5.0
#         with:
#           args: deploy --only hosting
#         env:
#           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}