name: Firebase Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch: # 手動トリガー

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      - name: Upload build artifacts  # 追加
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: dist

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: "npm"
      - name: Install firebase-tools
        run: npm install --save-dev firebase-tools
      - name: Decode Firebase service account key
        run: |
          echo "${{ secrets.FIREBASE_KEY }}" | base64 -d > ./firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-key.json" >> $GITHUB_ENV
      - name: Download build artifacts  # 追加
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: dist
      - name: change space
        run: ./node_modules/.bin/firebase use ${{ secrets.FIREBASE_PROJECT_ID }}
      - name: Deploy to Firebase Hosting
        run: |
          ./node_modules/.bin/firebase deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_CLI_EXPERIMENTS: webframeworks
      - name: delete GOOGLE_APPLICATION_CREDENTIALS
        run: rm $GOOGLE_APPLICATION_CREDENTIALS
        if: ${{ always() }}


      # - name: Install Firebase CLI
      #   # run: npm install -g firebase-tools # デフォルトのバージョンをインストールする場合
      #   # 使用例: プロジェクトごとに異なるバージョンのfirebase-toolsを使用したい場合や、CI/CDパイプラインで特定のバージョンを使用したい場合に便利
      #   run: npm install --save-dev firebase-tools
      # - name: Debug Firebase CLI
      #   run: firebase --version
      # - name: Deploy to Production
      #   run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}

# name: Firebase Deploy

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       # リポジトリのコードをチェックアウト（クローン）するために使用される
#       - uses: actions/checkout@v4
#       - name: Set up Node.js
#         # GitHubが提供する公式のNode.jsセットアップアクションです。このアクションを使うことで、ワークフロー内でNode.js環境を整えることができる
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20'
#       - run: npm install
#       - run: npm run build

#   deploy:
#     runs-on: ubuntu-latest
#     # GitHub Actionsのワークフロー内でジョブの依存関係を指定するために使用される
#     needs: build
#     steps:
#       - uses: actions/checkout@v4
#       - name: Install Firebase CLI
#         run: npm install -g firebase-tools
#       - name: Deploy to Production
#         run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}

# name: Firebase Deploy

# on:
#   push:
#     branches:
#     - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     # リポジトリのコードをチェックアウト（クローン）するために使用される
#       - uses: actions/checkout@v4
#       - name: Set up Node.js
#     # GitHubが提供する公式のNode.jsセットアップアクションです。このアクションを使うことで、ワークフロー内でNode.js環境を整えることができる
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20'
#       - run: npm install
#       - run: npm run build

#   deploy:
#     runs-on: ubuntu-latest
#     # GitHub Actionsのワークフロー内でジョブの依存関係を指定するために使用される
#     needs: build
#     steps:
#       - uses: actions/checkout@v4
#       - name: Deploy to Production
#       run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
#       # run: |
# # echo "Deploying to production server..."
# # # デプロイメントスクリプトをここに記述


# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#         with:
#           node-version: '12'
#       - run: npm ci
#       - run: npm run build
#       - name: GitHub Action for Firebase
#         uses: w9jds/firebase-action@v1.5.0
#         with:
#           args: deploy --only hosting
#         env:
#           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}